title: Edem de Youngster
logo: "/assets/imgs/stacked_badge_profile.JPG"
avatar: "/assets/imgs/Selectednobg.jpg"
round-avatar: false
# description: description
markdown: GFM # Set to use github.com markdown rendered in github.io
remote_theme: pages-themes/time-machine@v0.2.0
# remote_theme: pages-themes/midnight@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
